### ISSUE TITLE
Building base fails because of 404 for EPEL rpm

### ISSUE THREAD

**Issue by xyleen** [bijukunjummen/docker-rabbitmq-cluster#2]
```
curl: (22) The requested URL returned error: 404 Not Found
error: skipping http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm - transfer failed  
```

Found this link to be working:

```
ftp://fr2.rpmfind.net/linux/centos/7.0.1406/extras/x86_64/Packages/epel-release-7-2.noarch.rpm
```

**Comment by jay-johnson** [comment]
I hit this too. Looks like there's a newer version:
http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

Not sure if that's something a config could handle vs trying to lock down on using just the 7.2 version.
