### ISSUE TITLE
cannot startup

### ISSUE THREAD

**Issue by ghost** [bijukunjummen/docker-rabbitmq-cluster#4]
Win10 

ERROR: for rabbit1  Cannot start service rabbit1: driver failed programming external connectivity on endpoint cluster_ra
bbit1_1 (fd3e38f55e4e4a260f116f17bef5c4b988f690c9dbf172d0dcaed90e8979e503): Error starting userland proxy: mkdir /port/t
cp:0.0.0.0:15672:tcp:172.17.0.2:15672: input/output error
ERROR: Encountered errors while bringing up the project.

**Comment by muzuro** [comment]
Have same error, @suiwenfeng could you assist, what was reason? Or more correct to ask @bijukunjummen?
UPD. I have fixed it with(solution from https://github.com/docker/for-win/issues/573):
Stop all the running containers docker stop $(docker ps -a -q) then
Stop the Docker on your machine & restart it.
