### ISSUE TITLE
Support for ENV variables

### ISSUE THREAD

**Issue by mahi-kandiar** [bijukunjummen/docker-rabbitmq-cluster#6]
Please support RABBITMQ_DEFAULT_USER, RABBITMQ_DEFAULT_USER, etc like rabbitmq:3

**Comment by bijukunjummen** [comment]
Thanks @mahendran-ayyasamy. Can I request a PR from you, would be more than happy to merge it in and build the image and republish it to dockerhub.

**Comment by mahendran-ayyasamy** [comment]
sorry. what is a PR?

**Comment by bijukunjummen** [comment]
A git "Pull Request", basically if you have a good idea about how to make this change, go ahead and clone this project, make the changes and send me a PR that I can merge back to this codebase.

**Comment by mahi-kandiar** [comment]
Thanks. I added a pull request. thanks for the time

**Comment by mahi-kandiar** [comment]
rabbitmqctl delete_user guest will fail if start_app hasnt completed. if  rabbitmqctl wait /var/run/rabbitmq/pid wont work then should we just sleep 20 seconds?
